### PR TITLE
Complete CLEF support, sanitize data where necessary

### LINKED ISSUE #132: seq-ingest-gelf (seqcli) crash with invalid trace id
**Describe the bug**
When GELF is send to the ingest plugin and has an invalid @tr (not 32 hex digits) the seq-input-gelf docker container crashes.

**To Reproduce**
1. `nc -u localhost 12201`
2. Send the following string: `{"version":"1.1","host":"foo","timestamp":1771349856.12,"level":6,"short_message":"This is a test","@tr":"1234"}`
4. `docker compose logs seq-input-gelf` to see error
**Expected behavior**
An error should be printed to the seq-input-gelf logs indicating an invalid trace id. seqcli should not crash.

**Environment (please complete the following information):**
 - OS: Linux
 - Browser Firefox
 - Seq Version 2025.2.15571 (seq-input-gelf 3.0.458)
 - Using Docker? Yes

**Additional context**
docker-compose.yml:

```
services:
    seq-input-gelf:
        image: "datalust/seq-input-gelf:latest"
        depends_on:
            - seq
        ports:
            - "12202:12201/udp"
        environment:
            SEQ_ADDRESS: "http://seq:81"
            SEQ_SERVER_URL: "http://seq:80"
            GELF_ENABLE_DIAGNOSTICS: True
    seq:
        image: "datalust/seq:2025.2"
        ports:
            - "5341:80"
        environment:
            ACCEPT_EULA: Y
            SEQ_FIRSTRUN_ADMINPASSWORD: "password"
        volumes:
            - seq-data:/data
volumes:
    seq-data:
```

Error message and backtrace in logs:

```
Ingestion failed: Specified argument was out of the range of valid values. (Parameter 'idData')

System.ArgumentOutOfRangeException: Specified argument was out of the range of valid values. (Parameter 'idData')

   at System.Diagnostics.ActivityTraceId.CreateFromString(ReadOnlySpan`1 idData)

   at Serilog.Formatting.Compact.Reader.LogEventReader.ReadFromJObject(Int32 lineNumber, JObject jObject)

   at Serilog.Formatting.Compact.Reader.LogEventReader.ReadFromJObject(JObject jObject)

   at SeqCli.Ingestion.JsonLogEventReader.ReadFromJObject(JObject jObject) in /home/appveyor/projects/seqcli/src/SeqCli/Ingestion/JsonLogEventReader.cs:line 83

   at SeqCli.Ingestion.JsonLogEventReader.TryReadAsync() in /home/appveyor/projects/seqcli/src/SeqCli/Ingestion/JsonLogEventReader.cs:line 60

   at SeqCli.Ingestion.EnrichingReader.TryReadAsync() in /home/appveyor/projects/seqcli/src/SeqCli/Ingestion/EnrichingReader.cs:line 23

   at SeqCli.Ingestion.LogShipper.ReadBatchAsync(ILogEventReader reader, Func`2 filter, Int32 count, InvalidDataHandling invalidDataHandling, Int32 maxWaitMS) in /home/appveyor/projects/seqcli/src/SeqCli/Ingestion/LogShipper.cs:line 109

   at SeqCli.Ingestion.LogShipper.ShipEvents(SeqConnection connection, String apiKey, ILogEventReader reader, InvalidDataHandling invalidDataHandling, SendFailureHandling sendFailureHandling, Int32 batchSize, Func`2 filter) in /home/appveyor/projects/seqcli/src/SeqCli/Ingestion/LogShipper.cs:line 45

   at SeqCli.Cli.Commands.IngestCommand.Run() in /home/appveyor/projects/seqcli/src/SeqCli/Cli/Commands/IngestCommand.cs:line 117

thread 'main' panicked at library/std/src/io/stdio.rs:1118:9:

failed printing to stdout: Broken pipe (os error 32)

note: run with `RUST_BACKTRACE=1` environment variable to display a backtrace

{"@t":"2026-02-17T18:14:46.753920093Z","@l":"ERROR","@mt":"GELF input failed","@x":"failed printing to stdout: Broken pipe (os error 32)"}

```

### PR DESCRIPTION
**Pull request by nblumhardt**
This fixes #132 and expands CLEF support to all currently-accepted fields. To avoid unexpected behavior on pass-through, unrecognized `@` fields are escaped with `@@`.

There's a lot more we could do here, but I'm up against the end of my time-box for today.

### CODE REVIEW

File: sqelf/src/process.rs [hunk 1]
```diff
@@ -224,6 +227,53 @@ where
...
+        // Only numbers are useful on the Seq side; some legacy emitters create hex strings.
+        if let Some(event_type) = clef.event_type.take() {
+            match event_type {
+                Value::Null | Value::Bool(_) | Value::Array(_) | Value::Object(_) => {}
+                Value::Number(_) => {
+                    clef.event_type = Some(event_type);
+                }
+                Value::String(mut s) => {
+                    if s.starts_with("0x") {
+                        s = s[2..].to_owned();
```
Comment (KodrAus) [inline sqelf/src/process.rs]: Does this need to be owned?

Comment (nblumhardt) [reply sqelf/src/process.rs]: Ooh, no, it doesn't - thanks 👍

**Review by KodrAus — APPROVED** [review]
